const AUDIT_TYPES = {
  // Authentication related
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  PASSWORD_RESET: 'PASSWORD_RESET',
  
  // User related
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  
  // Defect related
  DEFECT_CREATE: 'DEFECT_CREATE',
  DEFECT_UPDATE: 'DEFECT_UPDATE',
  DEFECT_DELETE: 'DEFECT_DELETE',
  DEFECT_STATUS_CHANGE: 'DEFECT_STATUS_CHANGE',
  DEFECT_ASSIGN: 'DEFECT_ASSIGN',
  
  // Comment related
  COMMENT_CREATE: 'COMMENT_CREATE',
  COMMENT_UPDATE: 'COMMENT_UPDATE',
  COMMENT_DELETE: 'COMMENT_DELETE',
  
  // System related
  SYSTEM_CONFIG_CHANGE: 'SYSTEM_CONFIG_CHANGE',
  SYSTEM_BACKUP: 'SYSTEM_BACKUP',
  SYSTEM_RESTORE: 'SYSTEM_RESTORE'
};

module.exports = {
  AUDIT_TYPES
};
